// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdBxoq6C_8YEbNpqmqU0S4n9XWuLJsYmg',
    appId: '1:459196340607:web:b4bceb19620932873fe24a',
    messagingSenderId: '459196340607',
    projectId: 'holbegram-lb',
    authDomain: 'holbegram-lb.firebaseapp.com',
    storageBucket: 'holbegram-lb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgz61u_di2PEwXVNWhgNhjN-RvRDTTk_s',
    appId: '1:459196340607:android:327abd61646d26343fe24a',
    messagingSenderId: '459196340607',
    projectId: 'holbegram-lb',
    storageBucket: 'holbegram-lb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZW3txwXwN_Cl2J0kt7gLakOD7aYUBjbg',
    appId: '1:459196340607:ios:be77c77a5652e2f73fe24a',
    messagingSenderId: '459196340607',
    projectId: 'holbegram-lb',
    storageBucket: 'holbegram-lb.firebasestorage.app',
    iosBundleId: 'com.example.holbegram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZW3txwXwN_Cl2J0kt7gLakOD7aYUBjbg',
    appId: '1:459196340607:ios:be77c77a5652e2f73fe24a',
    messagingSenderId: '459196340607',
    projectId: 'holbegram-lb',
    storageBucket: 'holbegram-lb.firebasestorage.app',
    iosBundleId: 'com.example.holbegram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdBxoq6C_8YEbNpqmqU0S4n9XWuLJsYmg',
    appId: '1:459196340607:web:b8f788391de8b0d83fe24a',
    messagingSenderId: '459196340607',
    projectId: 'holbegram-lb',
    authDomain: 'holbegram-lb.firebaseapp.com',
    storageBucket: 'holbegram-lb.firebasestorage.app',
  );
}
